## Data Processing Configuration
dataset:
    type: "semantic_kitti"  # Options: "semantic_kitti", null
    # dataset_path: "/home/sustech/Dataset/semantickitti/semantickitti/dataset/sequences/"
    dataset_path: "/home/hejun/Dataset/semantickitti/semantickitti/dataset/sequences/"

    # sequences: ["00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10"]
    sequences: ["00"]

    # sequences: ["08"]
    
# Data Processing
processing:
    # Lidar processing
    use_patchwork: true  # 是否使用Patchwork++进行地面分割
    voxelmap:
        use_relation: true
        relation_threshold: 0.3
        voxel_size: 0.2
        max_frames: 50
        mode: "dirichlet"   # Options: "frequency", "bayesian", "maximal", "dirichlet"
        update_threshold: 1
        init_alpha: 1.
        use_key_frame: False
        key_frame_dist_thres: 1.0
        key_frame_angle_thres: 0.2 # radius

## Model Configuration
model_config:
    device: "cuda:0"
    DetectionModel:
        model_name: "GroundingDINO"
        # model_config_path: "/home/sustech/OpenVocabulary/lidar_photo/MyOpenProject/VLM/GroundingDINO/config/GroundingDINO_SwinT_OGC.py"
        # model_checkpoint_path: "/home/sustech/OpenVocabulary/lidar_photo/MyOpenProject/VLM/GroundingDINO/checkpoint/groundingdino_swint_ogc.pth"

        model_config_path: "/home/hejun/OpenVocabulary/lidar_photo/MyOpenProject/VLM/GroundingDINO/config/GroundingDINO_SwinT_OGC.py"
        model_checkpoint_path: "/home/hejun/OpenVocabulary/lidar_photo/MyOpenProject/VLM/GroundingDINO/checkpoint/groundingdino_swint_ogc.pth"

        use_cluster: true
        eps: 0.6
        min_samples: 20
        nms_iou_threshold: 0.5
        max_detections: 100
        box_threshold: 0.25
        text_threshold: 0.25
        nms_threshold: 0.5

    SegmentationModel:
        model_name: "SAM"
        encoder_version: "vit_h"
        # model_checkpoint_path: "/home/sustech/OpenVocabulary/lidar_photo/MyOpenProject/Segment_Module/segment-anything/checkpoint/sam_vit_h_4b8939.pth"
        model_checkpoint_path: "/home/hejun/OpenVocabulary/lidar_photo/MyOpenProject/Segment_Module/segment-anything/checkpoint/sam_vit_h_4b8939.pth"

        model_config_path: 

evaluation:
  reporting_mode: 'all' # 'global' 'per_sequence' 'all'

save:
    # output_path: "/home/sustech/OpenVocabulary/lidar_photo/MyOpenProject/outputs"
    output_path: "/home/hejun/OpenVocabulary/lidar_photo/MyOpenProject/outputs"

    save_local_points: true
    save_global_points: true
    save_segmented_images: true
    save_detection_images: true
    save_time: true
    save_label: true
    save_error_points: false
    save_pred_prob: true

external_feature:
    load_feature: false
    save_feature: true
    # feature_path: "/home/sustech/OpenVocabulary/lidar_photo/MyOpenProject/"
    feature_path: "/home/hejun/OpenVocabulary/lidar_photo/MyOpenProject/"

pcnetwork:
    use_net: false
    # net_feature_path: "/home/sustech/OpenVocabulary/lidar_photo/MyOpenProject/outputs/GroundingDINO_SAM/sequences/"
    net_feature_path: "/home/hejun/OpenVocabulary/lidar_photo/MyOpenProject/outputs/GroundingDINO_SAM/sequences/"